name: SylvessaPlugin
main: sylvessa.cb1337.Main
version: b1.8.1

commands:
  testc:
    description: Fucjkkkui8954iy89534u8t3u4t3uioy5hguiyh045tg
  help:
    description: Shows help info
  chatcolor:
    description: Lets you change your chat color.
  playerlist:
    description: yo
  hat:
    description: a
  sethome:
    description: a
  home:
    description: a
  createworld:
    description: a
  gwsdf:
    description: a
  tpa:
    description: a
  tpahere:
    description: a
  tpaccept:
    description: a
  tpdeny:
    description: a
  poop:
    description: a
  settings:
    description: a
  setting:
    description: a
  playerhomes:
    description: a
  rtp:
    description: a
  give2:
    description: a
  team:
    description: a
  teams:
    description: a
  spleef:
    description: a
  summon:
    description: a
  duel:
    description: a
  ride:
    description: a
  queue:
    description: a
  top:
    description: a