name: SylvessaPlugin
main: sylvessa.spigot.Main
version: 1.5.2

commands:
  testc:
    description: Fucjkkkui8954iy89534u8t3u4t3uioy5hguiyh045tg
  help:
    description: Shows help info
    usage: /help [page]
  chatcolor:
    description: Lets you change your chat color.
  playerlist:
    description: yo
    aliases: list
  hat:
    description: a
  sethome:
    description: a
  home:
    description: a
  tpa:
    description: a
  tpahere:
    description: a
  tpaccept:
    description: a
  tpdeny:
    description: a
  poop:
    description: a
  settings:
    description: a
  setting:
    description: a
  homes:
    description: a
  give2:
    description: a
  team:
    description: a
  teams:
    description: a
  summon:
    description: a
  duel:
    description: a
  ride:
    description: a
  queue:
    description: a
  top:
    description: a
  creative:
    description: a
  survival:
    description: a
  setblock:
    description: a
  enchantitem:
    description: a
  ping:
    description: a
  weather:
    description: a